
---
title: "Introduction"
---

So far, we have examined completely randomised designs where randomisation of experimental units to treatments was completely unrestricted. With complete randomisation, all other variables (the environment that we can never control completely) that might affect the response are, on average, equal in all treatment groups. This allows us to be confident that differences in group means are due to the treatments.  

However, there is often important variation in additional variables that we are not directly interested in. If we can group our experimental units with respect to these variables to make them more similar, we achieve a more powerful design. This is the idea of blocking.  

If blocks are used effectively, we can separate variability due to treatments, blocks, and errors, reducing unexplained variability. That is, variability between blocks can be estimated and removed from the residual error. Essentially, we compare treatments over more similar experimental units than in a completely randomised design. With reduced error variance, our test becomes more powerful.

Blocking is also useful when we want to demonstrate that treatment differences hold over a wider range of conditions. For example, in the social media multitasking example, the experiment was conducted on first year students. Strictly speaking, the results then only apply to first year students and extrapolation to students in different years of their degree is limited. Alternatively, we could choose students from first, second and third year (for example) and apply one replicate of each treatment within year. In this case, year of study would be the blocking factor.  

More generally, we often want to show that our results hold for different species, age groups, or  biological sexes. In such cases, we could use species, age, or sex as blocks. While blocks are typically used to control for variation in variables we are not directly interested in, sometimes these factors may also be of interest in their own right.  

### Treatments vs. Blocks  

When is a factor a treatment, and when is it a block?  

One way to distinguish between them is by asking whether we can manipulate the factor and randomly assign experimental units to its levels.  

- We generally cannot manipulate the age or sex of an individual, but we can manipulate, for example, the food they receive. So, age and sex are blocking factors, whereas food type is a treatment. 

- We can manipulate the level of social media multitasking, but we cannot manipulate the year of study of students. So, level of social media multitasking is a treatment, while year of study is a block.  

Although we can always estimate differences between blocks, we need to be much more cautious when inferring causality from block-level differences or rather from factors that we cannot randomise. The reason i add this last bit is because sometimes (and I know this is annoying), the treatment factor is also something that cannot be randomised! 

Suppose we are studying whether different music streaming platforms (e.g., Spotify, Apple Music, YouTube Music) influence a song's popularity. We cannot randomly assign a song to a particular streaming platform because artists typically release their music on multiple platforms simultaneously. However, platform choice is still the main factor of interest.

We would analyze differences in song popularity (e.g., number of streams, chart position) across platforms as we would for any treatment factor. However, we must be cautious when attributing differences solely to the platform itself because other factors could also play a role. For instance:

- Artist popularity: A well-known artist might naturally attract more streams, regardless of the platform.
- Marketing strategies: Some platforms might promote certain songs more aggressively.
- Release timing: Songs released during peak listening hours or days may perform better.
- Platform demographics: Different platforms cater to different audiences, which might influence engagement.

Since we cannot randomly assign songs to platforms, we cannot be certain that observed differences in popularity are only due to the platform. Instead, they may be influenced by a combination of these external factors.

Okay, so sometimes factors we cannot randomise are also treatment factors?! Yes, in the above example and in that constructed example about species and nitrate removal (can't randomise species to plants). The real difference is interest. We are not interested block effects on the response, only treatment effects. 

### Choosing Blocking Factors  

Any variable that might affect the response besides treatment factor should be considered for blocking. Common blocking factors include:  

- Space: field, site, placement within a field, greenhouse.  
- Time: experimental replication over different days or weeks.  
- Subject: person, animal, plant, genotype.  
- Equipment: container types, growth chambers.  

For example, if experimental units are tubs in a field, it is useful to arrange them into spatial blocks to control for field gradients. If an experiment spans multiple days, a good practice is to replicate all treatments on the first day, another set on the second day, and so on. In this case, day serves as the blocking factor, absorbing any environmental changes (e.g., temperature, humidity) rather than inflating the error variance.

Similarly, if experimental units must be distributed across multiple greenhouses, involve different container types or organisations, one approach is to assign a block per greenhouse or container type or organisation. This ensures that block effects are accounted for in the block variance rather than being mistaken for treatment effects.  

The key takeaway is that reducing error variance increases the power of the experiment. Thoughtful blocking design helps achieve this by accounting for known sources of variation.  

### Randomised Complete Block Design

There are a few different types of randomised block designs depending on the availity of experimental units and size of the blocks. Here we will consider the best case scenario, where blocks are big enough to contain an equal amount of experimental units such that each treatment coccurs exactly once within a block. If we have a single treatment factor with $a$ levels, then we have $a$ experimental units per block. This design is said to be *balanced*, each block is the same with respect to treatments. In balanced block designs, the treatment and block effects can be completely separated (are independent) . This greatly simplifies the interpretation of results. 

As in CRD, randomisation is still a crucial component of the design. The difference is that now $a$ treatments are assinged randomly to the $a$ experimental units within a block, i.e. randomisation is not complete over ALL experimental units but restricted within each block. Within each block, the experimental units are equally likely to recive any of the $a$ treatments. You can see this as CRD within each block! 

Let's see how we could randomise treatment within blocks using R. Imagine we had four treatments (A,B,C and D). We randomise the treatments to the units within one block like this:

```{r}

units <- 1:4
rbind(sample(units,4), rep(c("A","B","C","D")))


```

The third unit receive treatment A, the second receives B and so on. We then repeat this for every block. 

