project:
  type: book

book:
  title: "STA2020 ANOVA Notes"
  author: "Ané Cloete"
  date: "12/17/2024"
  chapters:
    - index.qmd
    - 00_ModelConcepts.qmd
    - part: "Experimental Design"
      chapters:
        - 01_ExpDesign_Why.qmd
        - 02_ExpDesign_Term.qmd
        - 03_ExpDesign_RRR.qmd
        - 04_ExpDesign_DesigningExp.qmd
        
    - part: "Single Factor Completely Randomised Designs"
      chapters:
      - 05_CRD_Intro.qmd
      - 06_CRD_Model.qmd
      - 07_CRD_ANOVA.qmd
      - 08_CRD_Contrasts.qmd
    
    - part: "Randomised Block Designs"
      chapters:
      - 09_RCBD_Model.qmd
      - 10_RCBD_ANOVA.qmd
      - 11_RCBD_Contrasts.qmd

    - part: "Factorial Experiments"
      chapters:
      - 12_FE_Model.qmd
      - 13_FE_ANOVA.qmd
    
    - glossary.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    fig_caption: true
    number-sections: true
    number-figures: true
    css: styles.css
  pdf:
    documentclass: scrreprt
    number-sections: true
    number-figures: true
    keep_tex: true
reference-location: margin
citation-location: margin
editor: visual

