project:
  type: book
  output-dir: docs

book:
  title: "STA2020 ANOVA Notes"
  author: "Ané Cloete"
  date: "12/17/2024"
  chapters:
    - index.qmd
    - 00_ModelConcepts.qmd
    - 00_HypoTesting.qmd
    - part: "Experimental Design"
      chapters:
        - 01_ExpDesign_Why.qmd
        - 02_ExpDesign_Term.qmd
        - 03_ExpDesign_RRR.qmd
        - 04_ExpDesign_DesigningExp.qmd
        
    - part: "Single Factor Completely Randomised Designs"
      chapters:
        - 05_CRD_Intro.qmd
        - 06_CRD_Model.qmd
        - 07_CRD_ANOVA.qmd
        - 08_CRD_Contrasts.qmd
    
 
bibliography: references.bib

format:
  html:
    theme: cosmo
    # number-sections: true
    # number-figures: true
    css: custom.css

  pdf:
    documentclass: book
    keep-tex: true
    output-file: pdf-book
    fig-pos: "H"  # Forces figures to stay close to the code
    link-citations: true
    highlight-style: tango  # Improves syntax highlighting
    keep-md: true

