project:
  type: book

book:
  title: "STA2020 ANOVA Notes"
  author: "Ané Cloete"
  date: "12/17/2024"
  chapters:
    - index.qmd
    - part: "Experimental Design"
      chapters:
        - 01_ExpDesign_Why.qmd
        - 02_ExpDesign_Term.qmd
        - 03_ExpDesign_RRR.qmd
    - part: "Completely Randomised Designs"

    - part: "Randomised Block Designs"

    - part: "Factorial Experiments"


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

